apiVersion: v1
kind: Namespace
metadata:
  name: starboard
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: starboard-operator
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://aquasecurity.github.io/helm-charts/

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: starboard-operator
  namespace: starboard-system
spec:
  chart:
    spec:
      chart: starboard-operator
      sourceRef:
        kind: HelmRepository
        name: starboard-operator
        namespace: flux-system
      version: 0.10.3
  interval: 1m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: starboard
  namespace: starboard
spec:
  interval: 3m
  path: ./kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: starboard-operator
  targetNamespace: default
  timeout: 3m0s
  wait: true